# Workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - master  # Adjust to your default branch if different
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.118.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to a version compatible with Node.js 20
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Build the site with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo --gc --minify -b ${{ github.repository_url }}/
      
      - name: Create .nojekyll
        run: echo "" > ./public/.nojekyll

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v2  # Updated to a version compatible with Node.js 20
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # Updated to a version compatible with Node.js 20
